[General]
hotkey_enabled = false
pipe_server_name = "watchdog"
active_profile = "Desktop Dual Monitor"
pipe_server_enabled = true
track_on_start = true
quit_on_loss_of_track_ir = false
trackir_dll_directory = ""
auto_find_trackir_dll = true
log_level = 5

[[Profiles]]
name = "Laptop"
profile_id = 2025
use_default_padding = true

[[Profiles.DisplayMappings]]
pad_bottom = 0
left = 21.0
right = -21.0
top = -15.0
bottom = 15.0
pad_top = 0
pad_left = 3
pad_right = 3

[[Profiles]]
profile_id = 13302
name = "Desktop Dual Monitor"
use_default_padding = true

[[Profiles.DisplayMappings]]
pad_bottom = 0
left = 43.0
right = -50.0
top = -20.0
bottom = 19.0
pad_top = 0
pad_left = 3
pad_right = 3
[[Profiles.DisplayMappings]]
left = -62.0
pad_bottom = 0
right = -180.0
top = -20.0
bottom = 19.0
pad_left = 3
pad_top = 0
pad_right = 3

[[Profiles]]
name = "Desktop Left Mon White Desk"
profile_id = 13302
use_default_padding = true

[[Profiles.DisplayMappings]]
pad_bottom = 0
left = -43.0
right = 50.0
top = -19.0
bottom = 19.0
pad_top = 0
pad_left = 3
pad_right = 3

[[Profiles]]
name = "Laptop2"
profile_id = 2025
use_default_padding = true

[[Profiles.DisplayMappings]]
pad_bottom = 0
left = 40.0
right = -40.0
top = -18.0
bottom = 18.0
pad_top = 0
pad_left = 0
pad_right = 0


[DefaultPadding]
left = 3
right = 3
top = 0
bottom = 0


