#ifndef TRACKIRMOUSE_CONTROL_IDS_H
#define TRACKIRMOUSE_CONTROL_IDS_H

#include <wx/wx.h>

enum
{
	myID_TRACK_ON_START = wxID_HIGHEST + 1,
	myID_WATCHDOG_ENABLED,
	myID_QUIT_ON_LOSS_OF_TRACK_IR,
	myID_TRACK_IR_DLL_PATH,
	myID_START_TRACK,
	myID_STOP_TRACK,
	myID_SAVE_SETTINGS,
	myID_PROFILE_SELECTION,
	myID_GEN_EXMPL,
	myID_TRACK_START,
};

#endif /* TRACKIRMOUSE_CONTROL_IDS_H */