#ifndef TRACKIRMOUSE_CONTROL_IDS_H
#define TRACKIRMOUSE_CONTROL_IDS_H

#include <wx/wx.h>

enum
{
	myID_TRACK_ON_START = wxID_HIGHEST + 1,
	myID_QUIT_ON_LOSS_OF_TRACK_IR,
	myID_START_MOUSE,
	myID_STOP_MOUSE,
	myID_SAVE_SETTINGS,
	myID_PROFILE_SELECTION,
	myID_GEN_EXMPL,
};

#endif /* TRACKIRMOUSE_CONTROL_IDS_H */