#ifndef TRACKIRMOUSE_CONTROL_IDS_H
#define TRACKIRMOUSE_CONTROL_IDS_H

#include <wx/wx.h>

enum ControlId
{
  myID_MENU_RELOAD_SETTINGS = wxID_HIGHEST + 1,
  myID_MENU_VIEW_LOGFILE
};

#endif /* TRACKIRMOUSE_CONTROL_IDS_H */
