#ifndef TRACKIRMOUSE_CONTROL_IDS_H
#define TRACKIRMOUSE_CONTROL_IDS_H

#include <wx/wx.h>

enum
{
  myID_MENU_RELOAD = wxID_HIGHEST + 1,
  myID_VIEW_LOGFILE,
  myID_MENU_SETTINGS,
  myID_START_TRACK,
  myID_STOP_TRACK,
  myID_PROFILE_SELECTION,
  myID_ADD_PROFILE,
  myID_REMOVE_PROFILE,
  myID_DUPLICATE_PROFILE,
  myID_PROFILE_NAME,
  myID_PROFILE_ID,
  myID_USE_DEFAULT_PADDING,
  myID_MANAGE_DISPLAYS,
  myID_MAPPING_DATA,
  myID_SETTINGS,
  myID_ADD_DISPLAY,
  myID_REMOVE_DISPLAY,
  myID_MOVE_UP,
  myID_MOVE_DOWN
};

#endif /* TRACKIRMOUSE_CONTROL_IDS_H */
