#pragma once
#ifndef TRACKIRMOUSE_VERSION_HPP
#define TRACKIRMOUSE_VERSION_HPP

#define TIRMOUSE_VER_MAJOR 1
#define TIRMOUSE_VER_MINOR 2
#define TIRMOUSE_VER_PATCH 0

#endif // TRACKIRMOUSE_VERSION_HPP
